name: Setup dependencies

inputs:
  path:
    description: Path to the checked out project
    required: true
  setup-node:
    description: Whether to setup Node or not
    default: 'false'
  php-version:
    required: true
    default: 8.5

runs:
  using: composite
  steps:

  - name: Set up PHP
    uses: shivammathur/setup-php@v2
    with:
      php-version: '${{ inputs.php-version }}'

  - name: Validate composer
    run: composer validate
    shell: bash
    working-directory: ./${{ inputs.path }}

  - name: Cache composer
    uses: actions/cache@v5
    with:
      path: ${{ inputs.path }}/vendor
      key: composer-v1-${{ inputs.path }}-${{ hashFiles(format('{0}/composer.lock', inputs.path))}}

  - name: Install composer dependencies
    run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    shell: bash
    working-directory: ./${{ inputs.path }}

  - name: Setup node
    if: inputs.setup-node == 'true'
    uses: actions/setup-node@v6
    with:
      cache: 'npm'
      cache-dependency-path: ${{ inputs.path }}

  - name: Install node dependencies
    if: inputs.setup-node == 'true'
    run: npm ci
    shell: bash
    working-directory: ./${{ inputs.path }}

