name: Setup project

inputs:
  path:
    description: Path to the checked out project
    required: true
  setup-node:
    description: Whether to setup Node or not
    default: 'false'
runs:
  using: composite
  steps:
  - name: Copy .env
    run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    shell: bash
    working-directory: ./${{ inputs.path }}

  - name: Validate composer
    run: composer validate
    shell: bash
    working-directory: ./${{ inputs.path }}

  - name: Cache composer
    uses: actions/cache@v3
    with:
      path: ${{ inputs.path }}/vendor
      key: composer-v1-${{ inputs.path }}-${{ hashFiles(format('{0}/composer.lock', inputs.path))}}

  - name: Install composer dependencies
    run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    shell: bash
    working-directory: ./${{ inputs.path }}

  - name: Setup node
    if: inputs.setup-node == 'true'
    uses: actions/setup-node@v3
    with:
      cache: 'npm'
      cache-dependency-path: ${{ inputs.path }}

  - name: Install node dependencies
    if: inputs.setup-node == 'true'
    run: npm ci
    shell: bash
    working-directory: ./${{ inputs.path }}

  - name: Generate key
    run: php artisan key:generate
    shell: bash
    working-directory: ./${{ inputs.path }}

  - name: Directory Permissions
    run: chmod -R 777 storage bootstrap/cache
    shell: bash
    working-directory: ./${{ inputs.path }}

  - name: Create Database
    run: |
      mkdir -p database
      touch database/testing.sqlite
    shell: bash
    working-directory: ./${{ inputs.path }}
