name: Setup project

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      setup-node:
        required: false
        type: boolean

jobs:
  setup-project:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.repository }}
    steps:
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Validate composer
      run: composer validate

    - name: Cache composer
      uses: actions/cache@v3
      with:
        path: ${{ inputs.repository }}/vendor
        key: composer-v1-${{ inputs.repository }}-${{ hashFiles(inputs.repository + 'composer.lock')}}

    - name: Install composer dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Setup node
      if: inputs.setup-node
      uses: actions/setup-node@v3
      with:
        cache: 'npm'

    - name: Install node dependencies
      if: inputs.setup-node
      run: npm ci

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mkdir -p database
        touch database/testing.sqlite
