<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CreatePositionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('positions', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('callsign', 30);
            $table->string('name', 30);
            $table->string('fir', 4);
        });

        // Denmark
        DB::table('positions')->insert([
            ['callsign' => 'EKAH_APP', 'name' => 'Aarhus Approach', 'fir' => 'EKDK'],
            ['callsign' => 'EKAH_TWR', 'name' => 'Aarhus Tower', 'fir' => 'EKDK'],
            ['callsign' => 'EKBI_APP', 'name' => 'Billund Approach', 'fir' => 'EKDK'],
            ['callsign' => 'EKBI_TWR', 'name' => 'Billund Tower', 'fir' => 'EKDK'],
            ['callsign' => 'EKBI_F_APP', 'name' => 'Billund Arrival', 'fir' => 'EKDK'],
            ['callsign' => 'EKCH_E_DEP', 'name' => 'Kastrup Departure', 'fir' => 'EKDK'],
            ['callsign' => 'EKCH_F_APP', 'name' => 'Kastrup Final', 'fir' => 'EKDK'],
            ['callsign' => 'EKCH_DEP', 'name' => 'Kastrup Departure', 'fir' => 'EKDK'],
            ['callsign' => 'EKCH_E_APP', 'name' => 'Copenhagen Approach', 'fir' => 'EKDK'],
            ['callsign' => 'EKCH_DEL', 'name' => 'Kastrup Delivery', 'fir' => 'EKDK'],
            ['callsign' => 'EKCH_GND', 'name' => 'Kastrup Apron', 'fir' => 'EKDK'],
            ['callsign' => 'EKCH_APP', 'name' => 'Copenhagen Approach', 'fir' => 'EKDK'],
            ['callsign' => 'EKCH_C_TWR', 'name' => 'Kastrup Tower', 'fir' => 'EKDK'],
            ['callsign' => 'EKCH_D_TWR', 'name' => 'Kastrup Tower', 'fir' => 'EKDK'],
            ['callsign' => 'EKCH_TWR', 'name' => 'Kastrup Tower', 'fir' => 'EKDK'],
            ['callsign' => 'EKCH_A_GND', 'name' => 'Kastrup Apron', 'fir' => 'EKDK'],
            ['callsign' => 'EKDK_CTR', 'name' => 'Copenhagen Control', 'fir' => 'EKDK'],
            ['callsign' => 'EKDK_B_CTR', 'name' => 'Copenhagen Control', 'fir' => 'EKDK'],
            ['callsign' => 'EKDK_C_CTR', 'name' => 'Copenhagen Control', 'fir' => 'EKDK'],
            ['callsign' => 'EKDK_D_CTR', 'name' => 'Copenhagen Control', 'fir' => 'EKDK'],
            ['callsign' => 'EKDK_S_CTR', 'name' => 'Copenhagen Control', 'fir' => 'EKDK'],
            ['callsign' => 'EKDK_N_CTR', 'name' => 'Copenhagen Control', 'fir' => 'EKDK'],
            ['callsign' => 'EKDK_V_CTR', 'name' => 'Copenhagen Control', 'fir' => 'EKDK'],
            ['callsign' => 'EKDK_I_CTR', 'name' => 'Copenhagen Information', 'fir' => 'EKDK'],
            ['callsign' => 'EKEB_I_TWR', 'name' => 'Esbjerg AFIS', 'fir' => 'EKDK'],
            ['callsign' => 'EKKA_APP', 'name' => 'Karup Approach', 'fir' => 'EKDK'],
            ['callsign' => 'EKKA_TWR', 'name' => 'Karup Tower', 'fir' => 'EKDK'],
            ['callsign' => 'EKOD_I_TWR', 'name' => 'Odense AFIS', 'fir' => 'EKDK'],
            ['callsign' => 'EKRK_APP', 'name' => 'Roskilde Approach', 'fir' => 'EKDK'],
            ['callsign' => 'EKRK_TWR', 'name' => 'Roskilde Tower', 'fir' => 'EKDK'],
            ['callsign' => 'EKRN_TWR', 'name' => 'Rønne Tower', 'fir' => 'EKDK'],
            ['callsign' => 'EKSB_I_TWR', 'name' => 'Sønderborg AFIS', 'fir' => 'EKDK'],
            ['callsign' => 'EKSP_TWR', 'name' => 'Skrydstrup Approach', 'fir' => 'EKDK'],
            ['callsign' => 'EKSP_APP', 'name' => 'Skrydstrup Approach', 'fir' => 'EKDK'],
            ['callsign' => 'EKYT_TWR', 'name' => 'Aalborg Tower', 'fir' => 'EKDK'],
            ['callsign' => 'EKYT_APP', 'name' => 'Aalborg Approach', 'fir' => 'EKDK'],
            ['callsign' => 'EKYT_F_APP', 'name' => 'Aalborg Arrival', 'fir' => 'EKDK']
        ]);

        // Finland
        DB::table('positions')->insert([
            ['callsign' => 'EFIN_A_CTR', 'name' => 'Helsinki Control', 'fir' => 'EFIN'],
            ['callsign' => 'EFIN_B_CTR', 'name' => 'Helsinki Control', 'fir' => 'EFIN'],
            ['callsign' => 'EFIN_C_CTR', 'name' => 'Helsinki Control', 'fir' => 'EFIN'],
            ['callsign' => 'EFIN_D_CTR', 'name' => 'Helsinki Control', 'fir' => 'EFIN'],
            ['callsign' => 'EFIN_E_CTR', 'name' => 'Helsinki Control', 'fir' => 'EFIN'],
            ['callsign' => 'EFIN_F_CTR', 'name' => 'Helsinki Control', 'fir' => 'EFIN'],
            ['callsign' => 'EFIN_G_CTR', 'name' => 'Helsinki Control', 'fir' => 'EFIN'],
            ['callsign' => 'EFIN_H_CTR', 'name' => 'Helsinki Control', 'fir' => 'EFIN'],
            ['callsign' => 'EFIN_J_CTR', 'name' => 'Helsinki Control', 'fir' => 'EFIN'],
            ['callsign' => 'EFIN_K_CTR', 'name' => 'Helsinki Control', 'fir' => 'EFIN'],
            ['callsign' => 'EFIN_L_CTR', 'name' => 'Helsinki Control', 'fir' => 'EFIN'],
            ['callsign' => 'EFIN_M_CTR', 'name' => 'Helsinki Control', 'fir' => 'EFIN'],
            ['callsign' => 'EFIN_N_CTR', 'name' => 'Helsinki Control', 'fir' => 'EFIN'],
            ['callsign' => 'EFIN_V_CTR', 'name' => 'Helsinki Control', 'fir' => 'EFIN'],
            ['callsign' => 'EFIN_Y_CTR', 'name' => 'Helsinki Control', 'fir' => 'EFIN'],
            ['callsign' => 'EFIN_Z_CTR', 'name' => 'Helsinki Control', 'fir' => 'EFIN'],
            ['callsign' => 'EFIN_Y_APP', 'name' => 'Helsinki Control', 'fir' => 'EFIN'],
            ['callsign' => 'EFIN_Z_APP', 'name' => 'Helsinki Control', 'fir' => 'EFIN'],
            ['callsign' => 'EFET_I_TWR', 'name' => 'Enontekio AFIS', 'fir' => 'EFIN'],
            ['callsign' => 'EFHA_APP', 'name' => 'Halli Radar', 'fir' => 'EFIN'],
            ['callsign' => 'EFHA_TWR', 'name' => 'Halli Tower', 'fir' => 'EFIN'],
            ['callsign' => 'EFHK_W_APP', 'name' => 'Helsinki Radar', 'fir' => 'EFIN'],
            ['callsign' => 'EFHK_E_APP', 'name' => 'Helsinki Radar', 'fir' => 'EFIN'],
            ['callsign' => 'EFHK_R_APP', 'name' => 'Helsinki Arrival', 'fir' => 'EFIN'],
            ['callsign' => 'EFHK_A_APP', 'name' => 'Helsinki Arrival', 'fir' => 'EFIN'],
            ['callsign' => 'EFHK_E_TWR', 'name' => 'Helsinki Tower', 'fir' => 'EFIN'],
            ['callsign' => 'EFHK_W_TWR', 'name' => 'Helsinki Tower', 'fir' => 'EFIN'],
            ['callsign' => 'EFHK_GND', 'name' => 'Helsinki Ground', 'fir' => 'EFIN'],
            ['callsign' => 'EFHK_DEL', 'name' => 'Helsinki Ground', 'fir' => 'EFIN'],
            ['callsign' => 'EFIV_TWR', 'name' => 'Ivalo Tower', 'fir' => 'EFIN'],
            ['callsign' => 'EFIV_I_TWR', 'name' => 'Ivalo AFIS', 'fir' => 'EFIN'],
            ['callsign' => 'EFJO_TWR', 'name' => 'Joensuu Tower', 'fir' => 'EFIN'],
            ['callsign' => 'EFJY_APP', 'name' => 'Jyvaskylä Radar', 'fir' => 'EFIN'],
            ['callsign' => 'EFJY_R_APP', 'name' => 'Jyvaskyla Arrival', 'fir' => 'EFIN'],
            ['callsign' => 'EFJY_TWR', 'name' => 'Jyväskylä Tower', 'fir' => 'EFIN'],
            ['callsign' => 'EFJY_GND', 'name' => 'Jyväskylä Ground', 'fir' => 'EFIN'],
            ['callsign' => 'EFKE_TWR', 'name' => 'Kemi Tower', 'fir' => 'EFIN'],
            ['callsign' => 'EFKI_I_TWR', 'name' => 'Kajaani AFIS', 'fir' => 'EFIN'],
            ['callsign' => 'EFKK_APP', 'name' => 'Kruunu Radar', 'fir' => 'EFIN'],
            ['callsign' => 'EFKK_TWR', 'name' => 'Kruunu Tower', 'fir' => 'EFIN'],
            ['callsign' => 'EFKS_TWR', 'name' => 'Kuusamo Tower', 'fir' => 'EFIN'],
            ['callsign' => 'EFKS_I_TWR', 'name' => 'Kuusamo AFIS', 'fir' => 'EFIN'],
            ['callsign' => 'EFKT_APP', 'name' => 'Kittilä Radar', 'fir' => 'EFIN'],
            ['callsign' => 'EFKT_TWR', 'name' => 'Kittilä Tower', 'fir' => 'EFIN'],
            ['callsign' => 'EFKT_I_TWR', 'name' => 'Kittila AFIS', 'fir' => 'EFIN'],
            ['callsign' => 'EFKU_APP', 'name' => 'Kuopio Radar', 'fir' => 'EFIN'],
            ['callsign' => 'EFKU_R_APP', 'name' => 'Kuopio Arrival', 'fir' => 'EFIN'],
            ['callsign' => 'EFKU_TWR', 'name' => 'Kuopio Tower', 'fir' => 'EFIN'],
            ['callsign' => 'EFLP_TWR', 'name' => 'Lappeenranta Tower', 'fir' => 'EFIN'],
            ['callsign' => 'EFMA_APP', 'name' => 'Mariehamn Radar', 'fir' => 'EFIN'],
            ['callsign' => 'EFMA_TWR', 'name' => 'Mariehamn Tower', 'fir' => 'EFIN'],
            ['callsign' => 'EFMI_I_TWR', 'name' => 'Mikkeli AFIS', 'fir' => 'EFIN'],
            ['callsign' => 'EFOU_APP', 'name' => 'Oulu Radar', 'fir' => 'EFIN'],
            ['callsign' => 'EFOU_TWR', 'name' => 'Oulu Tower', 'fir' => 'EFIN'],
            ['callsign' => 'EFPO_APP', 'name' => 'Pori Radar', 'fir' => 'EFIN'],
            ['callsign' => 'EFPO_TWR', 'name' => 'Pori Tower', 'fir' => 'EFIN'],
            ['callsign' => 'EFRO_APP', 'name' => 'Rovaniemi Radar', 'fir' => 'EFIN'],
            ['callsign' => 'EFRO_R_APP', 'name' => 'Rovaniemi Arrival', 'fir' => 'EFIN'],
            ['callsign' => 'EFRO_TWR', 'name' => 'Rovaniemi Tower', 'fir' => 'EFIN'],
            ['callsign' => 'EFRO_DEL', 'name' => 'Rovaniemi Delivery', 'fir' => 'EFIN'],
            ['callsign' => 'EFSA_I_TWR', 'name' => 'Savonlinna AFIS', 'fir' => 'EFIN'],
            ['callsign' => 'EFSI_I_TWR', 'name' => 'Seinajoki AFIS', 'fir' => 'EFIN'],
            ['callsign' => 'EFTP_APP', 'name' => 'Pirkkala Radar', 'fir' => 'EFIN'],
            ['callsign' => 'EFTP_R_APP', 'name' => 'Pirkkala Arrival', 'fir' => 'EFIN'],
            ['callsign' => 'EFTP_TWR', 'name' => 'Pirkkala Tower', 'fir' => 'EFIN'],
            ['callsign' => 'EFTP_GND', 'name' => 'Pirkkala Ground', 'fir' => 'EFIN'],
            ['callsign' => 'EFTU_APP', 'name' => 'Turku Radar', 'fir' => 'EFIN'],
            ['callsign' => 'EFTU_TWR', 'name' => 'Turku Tower', 'fir' => 'EFIN'],
            ['callsign' => 'EFUT_TWR', 'name' => 'Utti Tower', 'fir' => 'EFIN'],
            ['callsign' => 'EFVA_APP', 'name' => 'Vaasa Radar', 'fir' => 'EFIN'],
            ['callsign' => 'EFVA_TWR', 'name' => 'Vaasa Tower', 'fir' => 'EFIN']
        ]);

        // Iceland
        DB::table('positions')->insert([
            ['callsign' => 'BIRD_CTR', 'name' => 'Reykjavik Control', 'fir' => 'BIRD'],
            ['callsign' => 'BIRD_1_CTR', 'name' => 'Reykjavik Control', 'fir' => 'BIRD'],
            ['callsign' => 'BIRD_2_CTR', 'name' => 'Reykjavik Control', 'fir' => 'BIRD'],
            ['callsign' => 'BIRD_3_CTR', 'name' => 'Reykjavik Control', 'fir' => 'BIRD'],
            ['callsign' => 'BIRD_4_CTR', 'name' => 'Reykjavik Control', 'fir' => 'BIRD'],
            ['callsign' => 'BIRD_5_CTR', 'name' => 'Reykjavik Control', 'fir' => 'BIRD'],
            ['callsign' => 'BIRD_6_CTR', 'name' => 'Reykjavik Control', 'fir' => 'BIRD'],
            ['callsign' => 'BICC_FSS', 'name' => 'Iceland Radio', 'fir' => 'BIRD'],
            ['callsign' => 'BIKF_APP', 'name' => 'Keflavik Approach', 'fir' => 'BIRD'],
            ['callsign' => 'BIKF_F_APP', 'name' => 'Keflavik Approach', 'fir' => 'BIRD'],
            ['callsign' => 'BIKF_TWR', 'name' => 'Keflavik Tower', 'fir' => 'BIRD'],
            ['callsign' => 'BIKF_GND', 'name' => 'Keflavik Ground', 'fir' => 'BIRD'],
            ['callsign' => 'BIKF_2_GND', 'name' => 'Keflavik Ground', 'fir' => 'BIRD'],
            ['callsign' => 'BIKF_DEL', 'name' => 'Keflavik Delivery', 'fir' => 'BIRD'],
            ['callsign' => 'BIRK_APP', 'name' => 'Reykjavik Approach', 'fir' => 'BIRD'],
            ['callsign' => 'BIRK_TWR', 'name' => 'Reykjavik Tower', 'fir' => 'BIRD'],
            ['callsign' => 'BIRK_GND', 'name' => 'Reykjavik Ground', 'fir' => 'BIRD'],
            ['callsign' => 'BIAR_APP', 'name' => 'Akureyri Radar', 'fir' => 'BIRD'],
            ['callsign' => 'BIAR_TWR', 'name' => 'Akureyri Tower', 'fir' => 'BIRD'],
            ['callsign' => 'BIIS_I_TWR', 'name' => 'Ísafjörður Radio', 'fir' => 'BIRD'],
            ['callsign' => 'EKVG_I_TWR', 'name' => 'Vágar AFIS', 'fir' => 'BIRD'],
            ['callsign' => 'BIVM_I_TWR', 'name' => 'Vestmannaeyjar Information', 'fir' => 'BIRD'],
            ['callsign' => 'BIBA_I_TWR', 'name' => 'Bakki Information', 'fir' => 'BIRD'],
            ['callsign' => 'BIEG_I_TWR', 'name' => 'Egilsstadir Information', 'fir' => 'BIRD'],
            ['callsign' => 'BIBD_I_TWR', 'name' => 'Bildudalur Radio', 'fir' => 'BIRD'],
            ['callsign' => 'BIBL_I_TWR', 'name' => 'Blonduos Information', 'fir' => 'BIRD'],
            ['callsign' => 'BIGJ_I_TWR', 'name' => 'Gjogur Information', 'fir' => 'BIRD'],
            ['callsign' => 'BIGR_I_TWR', 'name' => 'Grimsey Information', 'fir' => 'BIRD'],
            ['callsign' => 'BIHK_I_TWR', 'name' => 'Holmavik Information', 'fir' => 'BIRD'],
            ['callsign' => 'BIHN_I_TWR', 'name' => 'Hornafjodur Radio', 'fir' => 'BIRD'],
            ['callsign' => 'BIHU_I_TWR', 'name' => 'Husavik Radio', 'fir' => 'BIRD'],
            ['callsign' => 'BINF_I_TWR', 'name' => 'Nordfjordur Information', 'fir' => 'BIRD'],
            ['callsign' => 'BIKR_I_TWR', 'name' => 'Saudarkrokur Radio', 'fir' => 'BIRD'],
            ['callsign' => 'BIRF_I_TWR', 'name' => 'Rif Information', 'fir' => 'BIRD'],
            ['callsign' => 'BITE_I_TWR', 'name' => 'Thingeyri Information', 'fir' => 'BIRD'],
            ['callsign' => 'BITN_I_TWR', 'name' => 'Thorshofn Radio', 'fir' => 'BIRD'],
            ['callsign' => 'BIVO_I_TWR', 'name' => 'Vopnafjordur Information', 'fir' => 'BIRD'],
            ['callsign' => 'BGGL_FSS', 'name' => 'Nuuk Information', 'fir' => 'BGGL'],
            ['callsign' => 'BGSF_TWR', 'name' => 'Søndrestrøm Tower', 'fir' => 'BGGL'],
            ['callsign' => 'BGSF_APP', 'name' => 'Søndrestrøm Approach', 'fir' => 'BGGL'],
            ['callsign' => 'BGBW_I_TWR', 'name' => 'Narsarsuaq AFIS', 'fir' => 'BGGL'],
            ['callsign' => 'BGGH_I_TWR', 'name' => 'Nuuk AFIS', 'fir' => 'BGGL'],
            ['callsign' => 'BGKK_I_TWR', 'name' => 'Kulusuk AFIS', 'fir' => 'BGGL'],
            ['callsign' => 'BGTL_APP', 'name' => 'Thule Approach', 'fir' => 'BGGL'],
            ['callsign' => 'BGTL_TWR', 'name' => 'Thule Tower', 'fir' => 'BGGL'],
            ['callsign' => 'BGTL_GND', 'name' => 'Thule Ground', 'fir' => 'BGGL'],
            ['callsign' => 'BGCO_TWR', 'name' => 'Constable Pynt Tower', 'fir' => 'BGGL']
        ]);

        // Norway
        DB::table('positions')->insert([
            ['callsign' => 'ENAL_APP', 'name' => 'Møre Approach', 'fir' => 'ENOR'],
            ['callsign' => 'ENAL_TWR', 'name' => 'Vigra Tower', 'fir' => 'ENOR'],
            ['callsign' => 'ENAN_APP', 'name' => 'Andøya Tower', 'fir' => 'ENOR'],
            ['callsign' => 'ENAN_TWR', 'name' => 'Andøya Tower', 'fir' => 'ENOR'],
            ['callsign' => 'ENAT_TWR', 'name' => 'Alta Tower', 'fir' => 'ENOR'],
            ['callsign' => 'ENAT_APP', 'name' => 'Alta Tower', 'fir' => 'ENOR'],
            ['callsign' => 'ENBD_H_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENBD_S_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENBD_9_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENBD_C_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENBD_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENBD_E_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENBL_I_TWR', 'name' => 'Bringeland Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENBN_I_TWR', 'name' => 'Brønnøy Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENBO_APP', 'name' => 'Bodø Approach', 'fir' => 'ENOR'],
            ['callsign' => 'ENBO_TWR', 'name' => 'Bodø Tower', 'fir' => 'ENOR'],
            ['callsign' => 'ENBO_GND', 'name' => 'Bodø Ground', 'fir' => 'ENOR'],
            ['callsign' => 'ENBR_W_APP', 'name' => 'Flesland Approach', 'fir' => 'ENOR'],
            ['callsign' => 'ENBR_E_APP', 'name' => 'Flesland Approach', 'fir' => 'ENOR'],
            ['callsign' => 'ENBR_D_APP', 'name' => 'Flesland Director', 'fir' => 'ENOR'],
            ['callsign' => 'ENBR_TWR', 'name' => 'Flesland Tower', 'fir' => 'ENOR'],
            ['callsign' => 'ENBR_GND', 'name' => 'Flesland Ground', 'fir' => 'ENOR'],
            ['callsign' => 'ENBS_I_TWR', 'name' => 'Båtsfjord Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENBV_I_TWR', 'name' => 'Berlevåg Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENCN_APP', 'name' => 'Kjevik Tower/Approach', 'fir' => 'ENOR'],
            ['callsign' => 'ENCN_TWR', 'name' => 'Kjevik Tower', 'fir' => 'ENOR'],
            ['callsign' => 'ENDU_APP', 'name' => 'Bardufoss Approach', 'fir' => 'ENOR'],
            ['callsign' => 'ENDU_TWR', 'name' => 'Bardufoss Tower', 'fir' => 'ENOR'],
            ['callsign' => 'ENEK_H_TWR', 'name' => 'Ekofisk Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENEV_TWR', 'name' => 'Evenes Tower', 'fir' => 'ENOR'],
            ['callsign' => 'ENEV_APP', 'name' => 'Evenes Tower/Approach', 'fir' => 'ENOR'],
            ['callsign' => 'ENFL_I_TWR', 'name' => 'Florø Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENGA_H_TWR', 'name' => 'Tampen Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENGK_I_TWR', 'name' => 'Gullknapp Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENGM_W_APP', 'name' => 'Oslo Approach', 'fir' => 'ENOR'],
            ['callsign' => 'ENGM_E_APP', 'name' => 'Oslo Approach', 'fir' => 'ENOR'],
            ['callsign' => 'ENGM_D_APP', 'name' => 'Oslo Director', 'fir' => 'ENOR'],
            ['callsign' => 'ENGM_F_APP', 'name' => 'Oslo Final', 'fir' => 'ENOR'],
            ['callsign' => 'ENGM_W_DEL', 'name' => 'Gardermoen Delivery West', 'fir' => 'ENOR'],
            ['callsign' => 'ENGM_W_TWR', 'name' => 'Gardermoen Tower West', 'fir' => 'ENOR'],
            ['callsign' => 'ENGM_2_APP', 'name' => 'Oslo Director', 'fir' => 'ENOR'],
            ['callsign' => 'ENGM_W_GND', 'name' => 'Gardermoen Ground West', 'fir' => 'ENOR'],
            ['callsign' => 'ENGM_E_DEL', 'name' => 'Gardermoen Delivery East', 'fir' => 'ENOR'],
            ['callsign' => 'ENGM_E_TWR', 'name' => 'Gardermoen Tower East', 'fir' => 'ENOR'],
            ['callsign' => 'ENGM_E_GND', 'name' => 'Gardermoen Ground East', 'fir' => 'ENOR'],
            ['callsign' => 'ENGM_Q_GND', 'name' => 'Gardermoen Ground', 'fir' => 'ENOR'],
            ['callsign' => 'ENHD_TWR', 'name' => 'Karmøy Tower', 'fir' => 'ENOR'],
            ['callsign' => 'ENHF_I_TWR', 'name' => 'Hammerfest Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENHK_I_TWR', 'name' => 'Hasvik Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENHV_I_TWR', 'name' => 'Valan Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENKB_APP', 'name' => 'Møre Approach', 'fir' => 'ENOR'],
            ['callsign' => 'ENKB_TWR', 'name' => 'Kvernberget Tower', 'fir' => 'ENOR'],
            ['callsign' => 'ENKR_TWR', 'name' => 'Kirkenes Tower', 'fir' => 'ENOR'],
            ['callsign' => 'ENKR_APP', 'name' => 'Kirkenes Tower', 'fir' => 'ENOR'],
            ['callsign' => 'ENLK_I_TWR', 'name' => 'Leknes Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENMH_I_TWR', 'name' => 'Mehamn Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENML_I_TWR', 'name' => 'Molde Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENMS_I_TWR', 'name' => 'Mosjøen Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENNA_TWR', 'name' => 'Banak TWR', 'fir' => 'ENOR'],
            ['callsign' => 'ENNA_APP', 'name' => 'Banak Tower', 'fir' => 'ENOR'],
            ['callsign' => 'ENNM_I_TWR', 'name' => 'Namsos Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENNO_I_TWR', 'name' => 'Notodden Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENOL_APP', 'name' => 'Ørland Approach', 'fir' => 'ENOR'],
            ['callsign' => 'ENOL_TWR', 'name' => 'Ørland Tower', 'fir' => 'ENOR'],
            ['callsign' => 'ENOL_A_APP', 'name' => 'Ørland Arrivial', 'fir' => 'ENOR'],
            ['callsign' => 'ENOR_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENOR_S_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENOS_1_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENOS_2_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENOS_3_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENOS_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENOS_5_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENOS_N_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENOS_7_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENOS_8_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENOV_I_TWR', 'name' => 'Hovden Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENRA_I_TWR', 'name' => 'Røssvoll Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENRM_I_TWR', 'name' => 'Rørvik Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENRO_APP', 'name' => 'Røros TWR', 'fir' => 'ENOR'],
            ['callsign' => 'ENRS_I_TWR', 'name' => 'Røst Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENRY_TWR', 'name' => 'Rygge Tower', 'fir' => 'ENOR'],
            ['callsign' => 'ENRY_APP', 'name' => 'Farris Approach', 'fir' => 'ENOR'],
            ['callsign' => 'ENSD_I_TWR', 'name' => 'Anda Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENSG_I_TWR', 'name' => 'Sogndal Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENSH_I_TWR', 'name' => 'Helle Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENSK_I_TWR', 'name' => 'Skagen Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENSO_I_TWR', 'name' => 'Sorstokken Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENSR_I_TWR', 'name' => 'Sørkjosen Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENSS_I_TWR', 'name' => 'Vardø Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENST_I_TWR', 'name' => 'Stokka Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENSV_O_CTR', 'name' => 'Norway Control (Offshore)', 'fir' => 'ENOR'],
            ['callsign' => 'ENSV_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENSV_N_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENSV_5_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENSV_4_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENSV_E_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENSV_0_CTR', 'name' => 'Norway Control', 'fir' => 'ENOR'],
            ['callsign' => 'ENTC_APP', 'name' => 'Tromsø Approach', 'fir' => 'ENOR'],
            ['callsign' => 'ENTC_TWR', 'name' => 'Tromsø Tower', 'fir' => 'ENOR'],
            ['callsign' => 'ENTO_APP', 'name' => 'Farris Approach', 'fir' => 'ENOR'],
            ['callsign' => 'ENTO_TWR', 'name' => 'Torp Tower', 'fir' => 'ENOR'],
            ['callsign' => 'ENTO_GND', 'name' => 'Torp Ground', 'fir' => 'ENOR'],
            ['callsign' => 'ENVA_APP', 'name' => 'Værnes Approach', 'fir' => 'ENOR'],
            ['callsign' => 'ENVA_D_APP', 'name' => 'Værnes Director', 'fir' => 'ENOR'],
            ['callsign' => 'ENVA_TWR', 'name' => 'Værnes Tower', 'fir' => 'ENOR'],
            ['callsign' => 'ENVA_GND', 'name' => 'Værnes Ground', 'fir' => 'ENOR'],
            ['callsign' => 'ENVD_I_TWR', 'name' => 'Vadsø Information', 'fir' => 'ENOR'],
            ['callsign' => 'ENZV_A_APP', 'name' => 'Sola Arrival', 'fir' => 'ENOR'],
            ['callsign' => 'ENZV_APP', 'name' => 'Sola Approach', 'fir' => 'ENOR'],
            ['callsign' => 'ENZV_D_APP', 'name' => 'Sola Director', 'fir' => 'ENOR'],
            ['callsign' => 'ENZV_TWR', 'name' => 'Sola Tower', 'fir' => 'ENOR'],
            ['callsign' => 'ENZV_GND', 'name' => 'Sola Ground', 'fir' => 'ENOR'],
            ['callsign' => 'ENAS_I_TWR', 'name' => 'Ny Ålesund Information', 'fir' => 'ENOB'],
            ['callsign' => 'ENJA_I_TWR', 'name' => 'Jan Mayen Information', 'fir' => 'ENOB'],
            ['callsign' => 'ENOB_CTR', 'name' => 'Bodø Oceanic Control', 'fir' => 'ENOB'],
            ['callsign' => 'ENSA_I_TWR', 'name' => 'Svea Information', 'fir' => 'ENOB'],
            ['callsign' => 'ENSB_I_TWR', 'name' => 'Longyear Information', 'fir' => 'ENOB']
        ]);

        // Sweden
        DB::table('positions')->insert([['callsign' => 'ESCF_TWR', 'name' => 'Malmen Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESCM_TWR', 'name' => 'Uppsala Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESCR_CTR', 'name' => 'Grizzly', 'fir' => 'ESAA'],
            ['callsign' => 'ESDF_TWR', 'name' => 'Ronneby Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESDF_APP', 'name' => 'Ronneby Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESDK_CTR', 'name' => 'Blue Shark', 'fir' => 'ESAA'],
            ['callsign' => 'ESFR_TWR', 'name' => 'Råda Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESFR_APP', 'name' => 'Råda Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESGG_E_APP', 'name' => 'Göteborg Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESGG_W_APP', 'name' => 'Göteborg Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESGG_F_APP', 'name' => 'Göteborg Arrival', 'fir' => 'ESAA'],
            ['callsign' => 'ESGG_TWR', 'name' => 'Landvetter Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESGG_GND', 'name' => 'Landvetter Ground', 'fir' => 'ESAA'],
            ['callsign' => 'ESGG_DEL', 'name' => 'Landvetter Clearance Delivery', 'fir' => 'ESAA'],
            ['callsign' => 'ESGJ_TWR', 'name' => 'Jönköping Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESGP_TWR', 'name' => 'Säve Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESGR_I_TWR', 'name' => 'Skövde Information', 'fir' => 'ESAA'],
            ['callsign' => 'ESGT_TWR', 'name' => 'Trollhättan Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESIA_TWR', 'name' => 'Karlsborg Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESIA_APP', 'name' => 'Karlsborg Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESIB_TWR', 'name' => 'Såtenäs Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESIB_APP', 'name' => 'Såtenäs Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESKM_I_TWR', 'name' => 'Mora Information', 'fir' => 'ESAA'],
            ['callsign' => 'ESKN_TWR', 'name' => 'Skavsta Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESKS_TWR', 'name' => 'Sälen Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESMK_TWR', 'name' => 'Kristianstad Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESMM_7_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESMM_5_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESMM_3_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESMM_2_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESMM_6_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESMM_4_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESMM_8_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESMM_9_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESMM_C_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESMM_K_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESMM_W_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESMM_Y_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESMQ_TWR', 'name' => 'Kalmar Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESMS_APP', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESMS_TWR', 'name' => 'Sturup Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESMS_GND', 'name' => 'Sturup Ground', 'fir' => 'ESAA'],
            ['callsign' => 'ESMT_TWR', 'name' => 'Halmstad Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESMV_TWR', 'name' => 'Hagshult Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESMV_APP', 'name' => 'Hagshult Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESMX_TWR', 'name' => 'Kronoberg Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESND_I_TWR', 'name' => 'Sveg Information', 'fir' => 'ESAA'],
            ['callsign' => 'ESNG_I_TWR', 'name' => 'Gällivare Information', 'fir' => 'ESAA'],
            ['callsign' => 'ESNJ_TWR', 'name' => 'Jokkmokk Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESNJ_APP', 'name' => 'Jokkmokk Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESNK_I_TWR', 'name' => 'Kramfors Information', 'fir' => 'ESAA'],
            ['callsign' => 'ESNL_I_TWR', 'name' => 'Lycksele Information', 'fir' => 'ESAA'],
            ['callsign' => 'ESNN_TWR', 'name' => 'Sundsvall Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESNO_TWR', 'name' => 'Örnsköldsvik Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESNQ_TWR', 'name' => 'Kiruna Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESNS_TWR', 'name' => 'Skellefteå Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESNU_TWR', 'name' => 'Umeå Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESNV_I_TWR', 'name' => 'Vilhelmina Information', 'fir' => 'ESAA'],
            ['callsign' => 'ESNX_TWR', 'name' => 'Arvidsjaur Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESNZ_TWR', 'name' => 'Östersund Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESOE_TWR', 'name' => 'Örebro Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESOH_I_TWR', 'name' => 'Hagfors Information', 'fir' => 'ESAA'],
            ['callsign' => 'ESOK_TWR', 'name' => 'Karlstad Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESOS_6_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESOS_1_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESOS_3_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESOS_4_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESOS_2_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESOS_8_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESOS_F_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESOS_7_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESOS_K_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESOS_N_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESOS_Y_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESOS_X_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESOS_9_CTR', 'name' => 'Sweden Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESOW_TWR', 'name' => 'Västerås Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESOW_APP', 'name' => 'Västerås Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESPA_TWR', 'name' => 'Kallax Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESPA_APP', 'name' => 'Kallax Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESPE_TWR', 'name' => 'Vidsel Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESPE_APP', 'name' => 'Vidsel Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESPF_CTR', 'name' => 'Cobra', 'fir' => 'ESAA'],
            ['callsign' => 'ESSA_W_APP', 'name' => 'Stockholm Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESSA_E_APP', 'name' => 'Stockholm Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESSA_W_DEP', 'name' => 'Stockholm Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESSA_F_APP', 'name' => 'Stockholm Arrival', 'fir' => 'ESAA'],
            ['callsign' => 'ESSA_A_APP', 'name' => 'Stockholm Arrival', 'fir' => 'ESAA'],
            ['callsign' => 'ESSA_W_TWR', 'name' => 'Arlanda Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESSA_E_TWR', 'name' => 'Arlanda Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESSA_S_TWR', 'name' => 'Arlanda Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESSA_N_GND', 'name' => 'Arlanda Ground', 'fir' => 'ESAA'],
            ['callsign' => 'ESSA_W_GND', 'name' => 'Arlanda Ground', 'fir' => 'ESAA'],
            ['callsign' => 'ESSA_E_GND', 'name' => 'Arlanda Ground', 'fir' => 'ESAA'],
            ['callsign' => 'ESSA_DEL', 'name' => 'Arlanda Clearance Delivery', 'fir' => 'ESAA'],
            ['callsign' => 'ESSA_E_DEP', 'name' => 'Stockholm Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESSB_APP', 'name' => 'Stockholm Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESSB_TWR', 'name' => 'Bromma Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESSB_GND', 'name' => 'Bromma Ground', 'fir' => 'ESAA'],
            ['callsign' => 'ESSD_TWR', 'name' => 'Borlänge Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESSL_TWR', 'name' => 'Saab Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESSP_APP', 'name' => 'Östgöta Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESSP_TWR', 'name' => 'Kungsängen Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESSR_CTR', 'name' => 'RTC Stockholm', 'fir' => 'ESAA'],
            ['callsign' => 'ESST_I_TWR', 'name' => 'Torsby Information', 'fir' => 'ESAA'],
            ['callsign' => 'ESSU_I_TWR', 'name' => 'Eskilstuna Information', 'fir' => 'ESAA'],
            ['callsign' => 'ESSV_TWR', 'name' => 'Visby Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESSV_APP', 'name' => 'Visby Control', 'fir' => 'ESAA'],
            ['callsign' => 'ESTA_TWR', 'name' => 'Ängelholm Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESTL_TWR', 'name' => 'Ljungbyhed Tower', 'fir' => 'ESAA'],
            ['callsign' => 'ESUP_I_TWR', 'name' => 'Pajala Information', 'fir' => 'ESAA'],
            ['callsign' => 'ESUT_I_TWR', 'name' => 'Hemavan Information', 'fir' => 'ESAA']
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('positions');
    }
}
