name: Linting

on:
  pull_request:
    branches:
      - master
      - 'version/**'

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Control Center
      uses: actions/checkout@v3
      with:
        path: .

    - name: Setup dependenices
      uses: .github/actions/setup-dependencies
      with:
        path: .

    - name: Check for incorrect formatting
      run: ./vendor/bin/pint --test
