---
# This workflow is used to release control-center. It runs an action that
# determines whether it needs to create a release or create a PR which
# contains a list of changes for the next release.
name: Release (release-please)

on:
  push:
    branches:
      - main
      - ci/release-please

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.VATSCA_BOT_TOKEN }}
